version: "3"

services:
  proxy:
    build:
      context: ./nginx
    container_name: proxy
    entrypoint:
      [
        "dockerize",
        "-wait",
        "tcp://app:3000",
        "-timeout",
        "25s",
        "/docker-entrypoint.sh",
      ]
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - app
  app:
    build:
      context: ./node
    container_name: app
    entrypoint:
      [
        "dockerize",
        "-wait",
        "tcp://db:3306",
        "-timeout",
        "20s",
        "node",
        "index.js",
      ]
    networks:
      - node-network
    tty: true
    volumes:
      - ./node:/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
networks:
  node-network:
    driver: bridge
